version: '3'
services:
  frontend:
    build: ./beacon-stats
    ports:
      - "3050:3000"
    environment:
      - NODE_ENV=development
      - VITE_IP_ADDRESS=${IP_ADDRESS}

  backend:
    build: ./beacon-stats-server
    ports:
      - "8050:8080"
    volumes:
      - ./config.yml:/usr/src/app/config.yml
    environment:
      - NODE_ENV=development
